[package]
name = "malachite-znz-fe"
version = "0.1.0"
edition = "2024"

[dependencies]
malachite = { version = "0.9.0", default-features = false, features = ["naturals_and_integers", "random"] }
rand = "0.9.2"

[dev-dependencies]
criterion = "0.8.1"
proptest = "1.9.0"
