[package]
name = "comparator"
version = "0.1.0"
edition = "2024"

[dependencies]
fuzzy_hashes = { path = "../fuzzy_hashes/" }
fe = { path = "../fe/" }

[dev-dependencies]
proptest = "1.10.0"
rand = "0.10.0-rc.8"