[package]
name = "ristretto-znz-fe"
version = "0.1.0"
edition = "2024"

[dependencies]
curve25519-dalek = { version = "5.0.0-pre.5", features = ["ff", "group", "rand_core"] }
num-bigint = "0.4.6"
num-traits = "0.2.19"
rand = { version = "0.10.0-rc.8" }

[dev-dependencies]
proptest = "1.9.0"
